name: '🧪 Test Case'
description: 'Create a new test case to ensure system quality.'
title: 'Test Case: [Feature or Component] - [Short Description]'
labels: ['test-case', 'backlog']
body:
  - type: markdown
    attributes:
      value: |
        ## CleanCity QA Test Case
        Please fill out the details below to create a new test case.

  - type: dropdown
    id: test-type
    attributes:
      label: 'Test Case Type'
      description: 'Select the category of this test case.'
      options:
        - 'Functional'
        - 'Non-functional'
        - 'UI/UX'
        - 'API'
        - 'Performance'
        - 'Security'
        - 'Regression'
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 'Priority'
      description: 'Set the priority for this test case.'
      options:
        - '🔴 High'
        - '🟡 Medium'
        - '🟢 Low'
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: 'Estimate'
      description: 'Estimate the effort required (e.g., 2h, 1d, 3p for story points).'
      placeholder: 'e.g., 4h'
    validations:
      required: false

  - type: textarea
    id: test-steps
    attributes:
      label: 'Test Steps'
      description: 'Provide a step-by-step description of how to perform the test.'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-results
    attributes:
      label: 'Expected Results'
      description: 'What is the expected outcome after performing the steps?'
      placeholder: 'The system should correctly calculate the total and display it.'
    validations:
      required: true
